import {
  DashboardOutlined,
  UserOutlined,
  TagOutlined,
  TagsOutlined,
  SettingOutlined,
  PieChartOutlined,
  DeploymentUnitOutlined,
} from '@ant-design/icons';

import DashboardPage from '@/pages/Dashboard';
import Generics from '@/pages/Generics';
import ProductCategory from '@/pages/ProductCategory';
import Product from '@/pages/Product';
import Position from '@/pages/Position';
import Employee from '@/pages/Employee';

export const sidebar = [
  // {
  //   id: 1,
  //   element: DashboardPage,
  //   title: 'Boshqaruv paneli',
  //   path: '/',
  //   isPrivate: true,
  //   role: ['admin'],
  //   icon: DashboardOutlined,
  //   hidden: false,
  //   items: [],
  // },
  {
    id: 2,
    element: Product,
    title: 'Mahsulotlar',
    path: '/product',
    isPrivate: true,
    role: ['admin'],
    icon: TagOutlined,
    hidden: false,
    items: [],
  },
  {
    id: 3,
    element: ProductCategory,
    title: 'Mahsulot kategoriyalari',
    path: 'product/category',
    isPrivate: true,
    role: ['admin'],
    icon: TagsOutlined,
    hidden: false,
    items: [],
  },
  {
    id: 4,
    element: Employee,
    title: 'Xodimlar',
    path: '/employee',
    isPrivate: true,
    role: ['admin'],
    icon: UserOutlined,
    hidden: false,
    items: [],
  },
  // {
  //   id: 7,
  //   element: Generics,
  //   title: 'Xodimlar fakturasi',
  //   path: '/employee-facotory',
  //   isPrivate: true,
  //   role: ['admin'],
  //   icon: PieChartOutlined,
  //   hidden: false,
  //   items: [],
  // },
  {
    id: 8,
    element: Position,
    title: 'Lavozim',
    path: '/employee-position',
    isPrivate: true,
    role: ['admin'],
    icon: DeploymentUnitOutlined,
    hidden: false,
    items: [],
  },
  // {
  //   id: 5,
  //   title: 'Sozlamalar',
  //   path: '/settings',
  //   isPrivate: true,
  //   role: ['admin'],
  //   icon: SettingOutlined,
  //   hidden: false,
  //   items: [
  //     {
  //       id: '5-1',
  //       parentId: 4,
  //       label: 'Admin',
  //       isPrivate: true,
  //       path: '/admin',
  //       role: ['admin'],
  //       element: Generics,
  //     },
  //     {
  //       id: '5-2',
  //       parentId: 4,
  //       label: 'Sozlamalar',
  //       isPrivate: true,
  //       path: '/settings',
  //       role: ['admin'],
  //       element: Generics,
  //     },
  //   ],
  // },
  // {
  //   id: 6,
  //   element: Generics,
  //   title: 'Profile',
  //   path: '/profile',
  //   isPrivate: true,
  //   role: ['admin'],
  //   icon: UserOutlined,
  //   hidden: true,
  //   items: [],
  // },
];
