import {
  DashboardOutlined,
  UserOutlined,
  TagOutlined,
  TagsOutlined,
  SettingOutlined,
  PieChartOutlined,
  DeploymentUnitOutlined,
  ContainerOutlined,
  CustomerServiceOutlined,
  ShopOutlined,
} from '@ant-design/icons';

import DashboardPage from '@/pages/Dashboard';
import Generics from '@/pages/Generics';
import ProductCategory from '@/pages/ProductCategory';
import Product from '@/pages/Product';
import Position from '@/pages/Position';
import Employee from '@/pages/Employee';
import Client from '@/pages/Client';
import PaymentMode from '@/pages/PaymentMode';
import { EmployeeAttendance } from '@/pages/EmployeeAttendance';
import Supplier from '@/pages/Supplier';
import SupplierInvoice from '@/pages/SupplierInvoice';

export const sidebar = [
  {
    id: 1,
    element: DashboardPage,
    title: 'Boshqaruv paneli',
    path: '/',
    isPrivate: true,
    role: ['admin'],
    icon: DashboardOutlined,
    hidden: false,
    items: [],
  },
  {
    id: 2,
    title: 'Ombor',
    path: '/product',
    isPrivate: true,
    role: ['admin'],
    icon: TagsOutlined,
    hidden: false,
    items: [
      {
        id: '2-1',
        parentId: 2,
        label: 'Mahsulotlar',
        isPrivate: true,
        path: '/product',
        role: ['admin'],
        element: Product,
      },
      {
        id: '2-2',
        parentId: 2,
        element: ProductCategory,
        label: 'Kategoriyalar',
        path: '/product/category',
        isPrivate: true,
        role: ['admin'],
      },
    ],
  },
  {
    id: 9,
    title: 'Yetkazib beruvchi',
    path: '/supplier',
    isPrivate: true,
    role: ['admin'],
    icon: ShopOutlined,
    hidden: false,
    items: [
      {
        id: '9-1',
        parentId: 9,
        element: Supplier,
        label: 'Kompaniyalar',
        isPrivate: true,
        path: '/supplier/list',
        role: ['admin'],
      },
      {
        id: '9-2',
        parentId: 9,
        element: SupplierInvoice,
        label: 'Hisob-fakturalar',
        path: '/supplier/invoice',
        isPrivate: true,
        role: ['admin'],
      },
    ],
  },
  // {
  //   id: 5,
  //   element: Client,
  //   title: 'Mijozlar',
  //   path: '/client',
  //   isPrivate: true,
  //   role: ['admin'],
  //   icon: CustomerServiceOutlined,
  //   hidden: false,
  //   items: [],
  // },
  // {
  //   id: 4,
  //   element: Generics,
  //   title: 'Hisob-fakturalar',
  //   path: '/invoice',
  //   isPrivate: true,
  //   role: ['admin'],
  //   icon: ContainerOutlined,
  //   hidden: false,
  // },
  {
    id: 3,
    title: 'Xodimlar',
    path: '/employee',
    isPrivate: true,
    role: ['admin'],
    icon: UserOutlined,
    hidden: false,
    items: [
      {
        id: '3-1',
        parentId: 3,
        element: Employee,
        label: "Xodimlar ro'yxati",
        path: '/employee',
        isPrivate: true,
        role: ['admin'],
      },
      {
        id: '3-2',
        parentId: 3,
        element: Position,
        label: 'Lavozim',
        path: '/employee/position',
        isPrivate: true,
        role: ['admin'],
      },
      {
        id: '3-3',
        parentId: 3,
        element: EmployeeAttendance,
        label: 'Davomat',
        path: '/employee/attendance',
        isPrivate: true,
        role: ['admin'],
      },
    ],
  },

  // {
  //   id: 7,
  //   element: Generics,
  //   title: 'Xodimlar fakturasi',
  //   path: '/employee-facotory',
  //   isPrivate: true,
  //   role: ['admin'],
  //   icon: PieChartOutlined,
  //   hidden: false,
  //   items: [],
  // },
  // {
  //   id: 8,
  //   element: Position,
  //   title: 'Lavozim',
  //   path: '/employee-position',
  //   isPrivate: true,
  //   role: ['admin'],
  //   icon: DeploymentUnitOutlined,
  //   hidden: false,
  //   items: [],
  // },
  // {
  //   id: 6,
  //   title: 'Sozlamalar',
  //   path: '/settings',
  //   isPrivate: true,
  //   role: ['admin'],
  //   icon: SettingOutlined,
  //   hidden: false,
  //   items: [
  //     {
  //       id: '5-1',
  //       parentId: 4,
  //       label: "To'lov usullari",
  //       isPrivate: true,
  //       path: '/payment/mode',
  //       role: ['admin'],
  //       element: PaymentMode,
  //     },
  // {
  //   id: '5-2',
  //   parentId: 4,
  //   label: 'Sozlamalar',
  //   isPrivate: true,
  //   path: '/settings',
  //   role: ['admin'],
  //   element: Generics,
  // },
  // ],
  // },
  // {
  //   id: 6,
  //   element: Generics,
  //   title: 'Profile',
  //   path: '/profile',
  //   isPrivate: true,
  //   role: ['admin'],
  //   icon: UserOutlined,
  //   hidden: true,
  //   items: [],
  // },
];
