name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Backendni build qilish
      - name: Set up Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: "20.14.0"

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Deploy backend to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          local-dir: airvent/backend/
          server-dir: /public_html/airvent/backend

      # Frontendni build qilish
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy frontend to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          local-dir: airvent/frontend/dist/
          server-dir: /public_html/airvent/frontend
