name: Deploy to cPanel

on:
  push:
    branches:
      - main # O'zingizning asosiy branchingizni belgilang

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Node.js versiyasini moslang

      - name: Install dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Upload backend files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.GIT_CPANEL_SERVER }}
          username: ${{ secrets.GIT_CPANEL_USER }}
          password: ${{ secrets.GIT_CPANEL_PWD }}
          port: 21
          local-dir: ./backend/
          server-dir: /public_html/backend/ # cPanel'dagi joylashuvni moslang

      - name: Upload frontend files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.GIT_CPANEL_SERVER }}
          username: ${{ secrets.GIT_CPANEL_USER }}
          password: ${{ secrets.GIT_CPANEL_PWD }}
          port: 21
          local-dir: ./frontend/dist/
          server-dir: /public_html/ # Frontend fayllari uchun joylashuv

      - name: Upload .htaccess file
        env:
          FTP_SERVER: ${{ secrets.GIT_CPANEL_SERVER }}
          FTP_USERNAME: ${{ secrets.GIT_CPANEL_USER }}
          FTP_PASSWORD: ${{ secrets.GIT_CPANEL_PWD }}
        run: |
          curl -T ./.htaccess --user $FTP_USERNAME:$FTP_PASSWORD ftp://$FTP_SERVER/public_html/.htaccess
