name: Deploy to cPanel

on:
  push:
    branches:
      - main # O'zingizning asosiy branchingizni belgilang

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Node.js versiyasini moslang

      - name: Install dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Install lftp
        run: sudo apt-get install lftp

      - name: Upload backend files
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -e "set ftp:ssl-allow no; mirror -R backend /public_html/backend; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER

      - name: Upload frontend files
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -e "set ftp:ssl-allow no; mirror -R frontend/dist /public_html; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER

      - name: Upload .htaccess file
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          curl -T ./.htaccess --user $FTP_USERNAME:$FTP_PASSWORD ftp://$FTP_SERVER:21/public_html/.htaccess
